#include "segarecomp/c_emitter.hpp"

#include <iomanip>
#include <sstream>
#include <string_view>

namespace segarecomp {
namespace {
[[nodiscard]] std::string c_string(std::string_view value) {
  std::ostringstream out;
  for (const char character : value) {
    const auto byte = static_cast<unsigned char>(character);
    if (character == '\\' || character == '"') out << '\\' << character;
    else if (character == '\n') out << "\\n";
    else if (character == '\r') out << "\\r";
    else if (character == '\t') out << "\\t";
    else if (byte >= 0x20U && byte <= 0x7eU) out << character;
    // Fixed-width octal escapes cannot consume a following hexadecimal digit.
    else out << '\\' << std::oct << std::setw(3) << std::setfill('0')
             << static_cast<unsigned>(byte) << std::dec;
  }
  return out.str();
}
} // namespace

std::string emit_c_manifest(const RomInfo &rom) {
  std::ostringstream out;
  out << "/* Metadata-only manifest generated by segarecomp; no image bytes or execution semantics. */\n"
         "#include <stddef.h>\n\n"
         "const char segarecomp_family[] = \"" << c_string(rom.family) << "\";\n"
       << "const char segarecomp_diagnostic[] = \"" << diagnostic_name(rom.diagnostic) << "\";\n"
       << "const size_t segarecomp_input_size = " << rom.size << "u;\n"
       << "const size_t segarecomp_size_limit = " << image_size_limit << "u;\n"
       << "const char segarecomp_outcome[] = \"" << outcome_name(rom.outcome) << "\";\n"
       << "const char segarecomp_inspection[] = \"" << c_string(format_inspection(rom)) << "\";\n";
  if (rom.family == "genesis") {
    out << "const char segarecomp_system_type[] = \"" << c_string(rom.system_type) << "\";\n"
        << "const char segarecomp_domestic_title[] = \"" << c_string(rom.domestic_title_display) << "\";\n";
  } else {
    out << "const char segarecomp_region_system[] = \"" << c_string(rom.region_system) << "\";\n"
        << "const unsigned segarecomp_rom_size_code = " << rom.rom_size_code << "u;\n";
  }
  return out.str();
}
} // namespace segarecomp
