#include "segarecomp/direct_flow.hpp"
#include <iostream>
#include <string>
#include <variant>
#include <vector>
namespace {
int failures{}; void expect(bool value, const char *message) { if (!value) { std::cerr << message << '\n'; ++failures; } }
segarecomp::DirectFlowProgram base(std::uint32_t end=0x108U) { segarecomp::DirectFlowProgram p{}; p.reset_entry.value=0x100U; p.mappings.push_back({"synthetic",{{},0x100U},{{},end},{0},{static_cast<std::uint64_t>(end-0x100U)}}); return p; }
template <typename Result> void has_rejection(const Result &result, segarecomp::DirectFlowDiagnostic category, const std::string &expected, const char *message) {
 const auto *failure=std::get_if<segarecomp::RejectedDirectFlow>(&result);
 expect(failure!=nullptr,message); // A negative must never quietly return analysis or execution.
 if(failure!=nullptr) expect(failure->category==category&&segarecomp::format_direct_flow_rejection(*failure)==expected,message);
}
template <typename Produce> void has_deterministic_discovery_rejection(Produce produce, segarecomp::DirectFlowDiagnostic category, const std::string &expected, const char *message) {
 const auto first=produce(); const auto repeated=produce();
 has_rejection(first,category,expected,message); has_rejection(repeated,category,expected,message);
 const auto *first_failure=std::get_if<segarecomp::RejectedDirectFlow>(&first); const auto *repeated_failure=std::get_if<segarecomp::RejectedDirectFlow>(&repeated);
 if(first_failure&&repeated_failure) expect(segarecomp::format_direct_flow_rejection(*first_failure)==segarecomp::format_direct_flow_rejection(*repeated_failure),message);
}
void accepted() {
 const std::vector<std::uint8_t> image{0x70,0x02,0x53,0x80,0x66,0xFC,0x60,0xFA}; auto a=segarecomp::discover_direct_flow(image,base()); const auto *ok=std::get_if<segarecomp::DirectFlowAnalysis>(&a);
 expect(ok&&ok->blocks.size()==3U&&ok->edges.size()==4U,"golden CFG"); if(!ok)return;
 expect(ok->blocks[0].operations[0].kind==segarecomp::DirectFlowIrKind::write_moveq_d0&&ok->blocks[0].provenance.id.entry.value==0x100U&&ok->blocks[0].provenance.entry_instruction.source.address.space==segarecomp::TargetAddressSpace::m68k_program&&ok->blocks[1].provenance.instructions.size()==2U&&ok->blocks[1].provenance.instructions[1].bytes==std::array<std::uint8_t,2>{0x66U,0xFCU},"complete block provenance retains ordered instruction evidence");
 segarecomp::DirectFlowState s{};s.pc.value=0x100U;s.sr=0x2700U;s.d={0x11111111U,0x22222222U,0x33333333U,0x44444444U,0x55555555U,0x66666666U,0x77777777U,0x88888888U}; auto r=segarecomp::execute_direct_flow(*ok,s,4);const auto *run=std::get_if<segarecomp::DirectFlowExecution>(&r);
 expect(run&&run->boundaries.size()==5U&&run->boundaries[0].incoming_is_reset_seed&&run->boundaries[1].outgoing_edge->kind==segarecomp::DirectEdgeKind::fallthrough&&run->boundaries[2].incoming_edge->kind==segarecomp::DirectEdgeKind::fallthrough&&run->boundaries[2].outgoing_edge->kind==segarecomp::DirectEdgeKind::bne_taken&&run->boundaries[3].incoming_edge->kind==segarecomp::DirectEdgeKind::bne_taken&&run->boundaries[3].outgoing_edge->kind==segarecomp::DirectEdgeKind::bne_fallthrough&&run->boundaries[4].outgoing_edge->kind==segarecomp::DirectEdgeKind::bra_taken&&run->final_state.d==std::array<std::uint32_t,8>{0U,0x22222222U,0x33333333U,0x44444444U,0x55555555U,0x66666666U,0x77777777U,0x88888888U}&&run->final_state.pc.value==0x102U&&run->final_state.sr==0x2704U,"ordered complete boundary state and edge evidence");
 s.pc.value=0x102U;s.d[0]=1U;auto fall=segarecomp::execute_direct_flow(*ok,s,2);expect(std::get<segarecomp::DirectFlowExecution>(fall).boundaries[1].outgoing_edge->kind==segarecomp::DirectEdgeKind::bne_fallthrough,"BNE fallthrough vector");
}
void subq_flags() {
 const std::vector<std::uint8_t> image{0x53,0x80,0x60,0xFE}; auto a=segarecomp::discover_direct_flow(image,base(0x104U)); const auto *analysis=std::get_if<segarecomp::DirectFlowAnalysis>(&a); expect(analysis!=nullptr,"SUBQ boundary analysis"); if(!analysis)return;
 struct Vector { std::uint32_t old; std::uint16_t expected_sr; std::uint32_t expected_d0; };
 const std::array<Vector,4> vectors{{{0U,0xA5F9U,0xFFFFFFFFU},{1U,0xA5E4U,0U},{0x80000000U,0xA5E2U,0x7FFFFFFFU},{0x80000001U,0xA5E8U,0x80000000U}}};
 for(const auto &vector:vectors) { segarecomp::DirectFlowState state{};state.pc.value=0x100U;state.sr=0xA5E0U;state.d={vector.old,0x11111111U,0x22222222U,0x33333333U,0x44444444U,0x55555555U,0x66666666U,0x77777777U};const auto result=segarecomp::execute_direct_flow(*analysis,state,1U);const auto *run=std::get_if<segarecomp::DirectFlowExecution>(&result);expect(run&&run->final_state.d==std::array<std::uint32_t,8>{vector.expected_d0,0x11111111U,0x22222222U,0x33333333U,0x44444444U,0x55555555U,0x66666666U,0x77777777U}&&run->final_state.pc.value==0x102U&&run->final_state.sr==vector.expected_sr&&run->boundaries[1].outgoing_edge->source_instruction.bytes==std::array<std::uint8_t,2>{0x53U,0x80U},"SUBQ.L full state and boundary flags"); }
}
void negatives() {
  const std::string prefix="{\"category\":\"";
  const auto record=[&](const std::string &category,const std::string &block,const std::string &source,const std::string &offset,const std::string &available,const std::string &requested,const std::string &length,const std::string &raw,const std::string &target,const std::string &claims="[]",const std::string &reason="null") { return prefix+category+"\",\"cpu_variant\":\"mc68000\",\"block_entry\":\""+block+"\",\"source_address\":"+source+",\"image_offset\":"+offset+",\"available_bytes\":"+available+",\"requested_length\":"+requested+",\"instruction_length\":"+length+",\"raw_bytes\":"+raw+",\"target\":"+target+",\"edge\":"+(target=="null"?"null":"true")+",\"mapping_claims\":"+claims+",\"unresolved_reason\":"+reason+"}"; };
  const std::string p100="{\"space\":\"m68k_program\",\"value\":\"0x00000100\"}", p103="{\"space\":\"m68k_program\",\"value\":\"0x00000103\"}", p104="{\"space\":\"m68k_program\",\"value\":\"0x00000104\"}", p180="{\"space\":\"m68k_program\",\"value\":\"0x00000180\"}", p102="{\"space\":\"m68k_program\",\"value\":\"0x00000102\"}";
  has_deterministic_discovery_rejection([&]{return segarecomp::discover_direct_flow(std::vector<std::uint8_t>{0x66,0x00},base(0x102U));},segarecomp::DirectFlowDiagnostic::truncated_instruction,record("truncated_instruction","0x00000100",p100,"0","2","4","2","\"6600\"","null"),"truncated instruction complete deterministic rejection");
  has_deterministic_discovery_rejection([&]{return segarecomp::discover_direct_flow(std::vector<std::uint8_t>{0x60,0x01},base(0x102U));},segarecomp::DirectFlowDiagnostic::odd_direct_target,record("odd_direct_target","0x00000100",p100,"0","0","0","null","\"6001\"",p103),"odd direct target complete deterministic rejection");
  has_deterministic_discovery_rejection([&]{return segarecomp::discover_direct_flow(std::vector<std::uint8_t>{0x60,0x7E},base(0x102U));},segarecomp::DirectFlowDiagnostic::unmapped_direct_target,record("unmapped_direct_target","0x00000100",p100,"0","0","0","null","\"607E\"",p180),"unmapped direct target complete deterministic rejection");
  auto conflict=base(0x102U);conflict.mappings.push_back({"low_copy",{{},0x104U},{{},0x106U},{0},{2}});conflict.mappings.push_back({"high_copy",{{},0x104U},{{},0x106U},{2},{4}});const std::string claims="[{\"name\":\"low_copy\",\"target_span\":[\"0x00000104\",\"0x00000106\"],\"image_offset_span\":[0,2]},{\"name\":\"high_copy\",\"target_span\":[\"0x00000104\",\"0x00000106\"],\"image_offset_span\":[2,4]}]";has_deterministic_discovery_rejection([&]{return segarecomp::discover_direct_flow(std::vector<std::uint8_t>{0x60,0x02,0x4E,0x71},conflict);},segarecomp::DirectFlowDiagnostic::conflicting_address_mapping,record("conflicting_address_mapping","0x00000100",p100,"0","0","0","null","\"6002\"",p104,claims),"conflicting mapping complete ordered rejection");
  auto middle=base(0x106U);middle.reset_entry.value=0x104U;middle.structural_intervals.push_back({{{},{{},0x100U},{0}},{{0x60,0x00}},{4}});has_deterministic_discovery_rejection([&]{return segarecomp::discover_direct_flow(std::vector<std::uint8_t>{0x60,0x00,0x00,0x04,0x60,0xFC},middle);},segarecomp::DirectFlowDiagnostic::mid_instruction_direct_target,record("mid_instruction_direct_target","0x00000104",p104,"4","0","0","null","\"60FC\"",p102),"mid-instruction target complete deterministic rejection");
  has_deterministic_discovery_rejection([&]{return segarecomp::discover_direct_flow(std::vector<std::uint8_t>{0x4E,0x71},base(0x102U));},segarecomp::DirectFlowDiagnostic::valid_but_unsupported_instruction,record("valid_but_unsupported_instruction","0x00000100",p100,"0","2","2","2","\"4E71\"","null"),"unsupported instruction complete deterministic rejection");
  auto unresolved=base(0x106U);unresolved.unresolved_targets.push_back({{},0x104U});auto a=segarecomp::discover_direct_flow(std::vector<std::uint8_t>{0x60,0x02,0x70,0x00,0x60,0xFC},unresolved);if(const auto *analysis=std::get_if<segarecomp::DirectFlowAnalysis>(&a)){segarecomp::DirectFlowState state{};state.pc.value=0x100U;const auto first=segarecomp::execute_direct_flow(*analysis,state,1);const auto repeated=segarecomp::execute_direct_flow(*analysis,state,1);const auto expected=record("reached_unresolved_direct_edge","0x00000100",p100,"0","0","0","null","\"6002\"",p104,"[]","\"persisted_unresolved\"");has_rejection(first,segarecomp::DirectFlowDiagnostic::reached_unresolved_direct_edge,expected,"reached unresolved edge complete rejection");has_rejection(repeated,segarecomp::DirectFlowDiagnostic::reached_unresolved_direct_edge,expected,"reached unresolved edge repeat rejection");const auto *first_failure=std::get_if<segarecomp::RejectedDirectFlow>(&first);const auto *repeated_failure=std::get_if<segarecomp::RejectedDirectFlow>(&repeated);if(first_failure&&repeated_failure)expect(segarecomp::format_direct_flow_rejection(*first_failure)==segarecomp::format_direct_flow_rejection(*repeated_failure),"reached unresolved edge deterministic rejection");}else expect(false,"unresolved edge requires a persisted analysis, not a discovery rejection");
}
} int main(){accepted();subq_flags();negatives();return failures==0?0:1;}
