#!/usr/bin/env python3
"""Materialize the project-owned manifest and assert the public CLI contract."""
import hashlib
import json
import random
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "tests/fixtures/header-classification-fixtures.json"

def number(value): return int(value, 0) if isinstance(value, str) else value
def decode_title(value): return value.encode("utf-8").decode("unicode_escape").encode("latin1")
def materialize(entry):
    size = number(entry["size"])
    data = bytearray(random.Random(entry["seed"]).randbytes(size) if "seed" in entry else size)
    def put(offset, value):
        start = number(offset)
        if start < size: data[start:min(size, start + len(value))] = value[:max(0, size - start)]
    systems = {"mega": b"SEGA MEGA DRIVE ", "genesis": b"SEGA GENESIS    ", "unsupported": b"SEGA 32X        ", "mega-prefix-15": b"SEGA MEGA DRIVE"}
    if "system" in entry: put("0x100", systems[entry["system"]])
    if "title" in entry: put("0x120", decode_title(entry["title"]) + b" " * (48 - len(decode_title(entry["title"]))))
    for offset, text in entry.get("writes", []): put(offset, text.encode("ascii"))
    sms = entry.get("sms", [])
    if sms and isinstance(sms[0], str): sms = [sms]
    for offset, region, low in sms:
        put(offset, b"TMR SEGA")
        if number(offset) + 15 < size: data[number(offset) + 15] = (region << 4) | low
    return bytes(data)

def hex_bytes(value): return value.hex().upper()
def c_string(value):
    escaped = []
    for character in value:
        if character in '\\\\"': escaped.append("\\" + character)
        elif character == "\n": escaped.append("\\n")
        elif character == "\r": escaped.append("\\r")
        elif character == "\t": escaped.append("\\t")
        elif 0x20 <= ord(character) <= 0x7e: escaped.append(character)
        else: escaped.append(f"\\{ord(character):03o}")
    return "".join(escaped)

def expected_emitted_manifest(entry, data):
    diagnostic = entry["expect"][1]
    if entry.get("system") in ("mega", "genesis"):
        title = data[0x120:0x150].rstrip(b" ")
        display = "".join(chr(value) if 0x20 <= value <= 0x7e else f"\\x{value:02X}" for value in title)
        system_type = "mega_drive" if entry["system"] == "mega" else "genesis"
        return (
            "/* Metadata-only manifest generated by segarecomp; no image bytes or execution semantics. */\n"
            "#include <stddef.h>\n\n"
            "const char segarecomp_family[] = \"genesis\";\n"
            f"const char segarecomp_diagnostic[] = \"{diagnostic}\";\n"
            f"const size_t segarecomp_input_size = {len(data)}u;\n"
            "const size_t segarecomp_size_limit = 4194304u;\n"
            "const char segarecomp_outcome[] = \"recognized\";\n"
            f"const char segarecomp_inspection[] = \"{c_string(expected_recognized(entry, data))}\";\n"
            f"const char segarecomp_system_type[] = \"{system_type}\";\n"
            f"const char segarecomp_domestic_title[] = \"{c_string(display)}\";\n"
        )
    sms = entry["sms"] if isinstance(entry["sms"][0], str) else entry["sms"][0]
    _, region, low = sms
    family, region_system = {
        3: ("master_system", "sms_japan"), 4: ("master_system", "sms_export"),
        5: ("game_gear", "gg_japan"), 6: ("game_gear", "gg_export"),
        7: ("game_gear", "gg_international"),
    }[region]
    return (
        "/* Metadata-only manifest generated by segarecomp; no image bytes or execution semantics. */\n"
        "#include <stddef.h>\n\n"
        f"const char segarecomp_family[] = \"{family}\";\n"
        f"const char segarecomp_diagnostic[] = \"{diagnostic}\";\n"
        f"const size_t segarecomp_input_size = {len(data)}u;\n"
        "const size_t segarecomp_size_limit = 4194304u;\n"
        "const char segarecomp_outcome[] = \"recognized\";\n"
        f"const char segarecomp_inspection[] = \"{c_string(expected_recognized(entry, data))}\";\n"
        f"const char segarecomp_region_system[] = \"{region_system}\";\n"
        f"const unsigned segarecomp_rom_size_code = {low}u;\n"
    )

def expected_recognized(entry, data):
    system = entry.get("system")
    if system in ("mega", "genesis"):
        system_bytes = data[0x100:0x110]; title = data[0x120:0x150]
        display = "".join(chr(v) if 0x20 <= v <= 0x7e else f"\\x{v:02X}" for v in title.rstrip(b" "))
        system_type = "mega_drive" if system == "mega" else "genesis"
        candidate = (f"- kind: genesis\n  offset: 0x100\n  status: valid\n  system-range: [0x100,0x110)\n"
                     f"  domestic-title-range: [0x120,0x150)\n  system-bytes: {hex_bytes(system_bytes)}\n  domestic-title-bytes: {hex_bytes(title)}\n")
        extra = f"family: genesis\nsystem-type: {system_type}\ndomestic-title-bytes: {hex_bytes(title)}\ndomestic-title-display: {display}\ndomestic-title-encoding: ascii_with_hex_escapes\n"
    else:
        sms = entry["sms"] if isinstance(entry["sms"][0], str) else entry["sms"][0]
        offset, region, low = number(sms[0]), sms[1], sms[2]
        family, region_system = ({3:("master_system","sms_japan"),4:("master_system","sms_export"),5:("game_gear","gg_japan"),6:("game_gear","gg_export"),7:("game_gear","gg_international")}[region])
        candidate = f"- kind: sms_gg\n  offset: 0x{offset:X}\n  status: valid\n  header-range: [0x{offset:X},0x{offset + 16:X})\n"
        extra = f"family: {family}\nregion-system: {region_system}\nrom-size-code: {low}\n"
    return f"input-size: {len(data)}\nsize-limit: 4194304\noutcome: recognized\ndiagnostic: {entry['expect'][1]}\ncandidates:\n{candidate}{extra}"

def main():
    executable = Path(sys.argv[1])
    manifest = json.loads(MANIFEST.read_text()); entries = manifest["fixtures"]; hashes = manifest["sha256"]
    with tempfile.TemporaryDirectory() as temporary:
        temporary = Path(temporary)
        for entry in entries:
            if not isinstance(entry.get("purpose"), str) or not entry["purpose"].strip():
                raise AssertionError(f"{entry.get('id', '<unnamed>')}: missing fixture purpose")
            data = materialize(entry)
            digest = hashlib.sha256(data).hexdigest()
            if hashes.get(entry["id"]) != digest: raise AssertionError(f"{entry['id']}: SHA-256 mismatch: {digest}")
            image = temporary / f"{entry['id']}.bin"; image.write_bytes(data)
            inspected = subprocess.run([executable, "inspect", image], text=True, capture_output=True, check=False)
            expected_status = 0 if entry["expect"][0] == "recognized" else 1
            if inspected.returncode != expected_status or f"outcome: {entry['expect'][0]}\ndiagnostic: {entry['expect'][1]}\n" not in inspected.stdout:
                raise AssertionError(f"{entry['id']}: inspect status/output mismatch: {inspected.returncode} {inspected.stdout!r}")
            if expected_status == 0 and inspected.stdout != expected_recognized(entry, data):
                raise AssertionError(f"{entry['id']}: inspect text mismatch\n{inspected.stdout}")
            emitted = subprocess.run([executable, "emit-c", image], text=True, capture_output=True, check=False)
            if emitted.returncode != expected_status: raise AssertionError(f"{entry['id']}: emit-c status mismatch")
            if expected_status == 0:
                expected_manifest = expected_emitted_manifest(entry, data)
                if emitted.stdout != expected_manifest or emitted.stderr:
                    raise AssertionError(f"{entry['id']}: emit-c text mismatch\n{emitted.stdout!r}\n{emitted.stderr!r}")
                repeated = subprocess.run([executable, "emit-c", image], text=True, capture_output=True, check=False)
                if repeated.returncode != 0 or repeated.stdout != emitted.stdout or repeated.stderr != emitted.stderr:
                    raise AssertionError(f"{entry['id']}: emit-c output is not repeatable")
            elif emitted.stdout or emitted.stderr != f"segarecomp: {entry['expect'][1]}\n": raise AssertionError(f"{entry['id']}: emit-c diagnostic mismatch")
    print(f"validated {len(entries)} synthetic fixtures")
if __name__ == "__main__": main()
