#!/usr/bin/env python3
"""SEG-047 (ADR 0096): deterministic generator of the checked-in native model table from the committed canonical model JSON.

The product build never runs this (the generated `.inc` is checked in); `--check` is the drift test used by CI/tests. Pure Python stdlib.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MODEL = ROOT / "tools" / "segarecomp_ml_region.model.json"
OUTPUT = ROOT / "platforms" / "genesis" / "machine" / "src" / "ml_region_model_v1_data.inc"


def render(model_bytes: bytes) -> str:
    model = json.loads(model_bytes)
    n = model["feature_count"]
    if (n != 141 or len(model["folded_weight"]) != n or len(model["feature_names"]) != n or model["window_bytes"] != 512
            or model["feature_version"] != "seg046-features-v1"):
        raise SystemExit("unexpected model shape")
    lines = [
        "// GENERATED by tools/segarecomp_ml_region_native_data.py from tools/segarecomp_ml_region.model.json. DO NOT EDIT.",
        "// SEG-047 (ADR 0096). Generic learned aggregate parameters only; binary64 shortest round-trip decimal literals.",
        f'inline constexpr const char *ml_source_model_sha256 = "{hashlib.sha256(model_bytes).hexdigest()}";',
        f'inline constexpr const char *ml_feature_version = "{model["feature_version"]}";',
        f'inline constexpr const char *ml_feature_schema_sha256 = "{model["feature_schema_sha256"]}";',
        f'inline constexpr const char *ml_original_artifact_sha256 = "{model["original_sklearn_artifact_sha256"]}";',
        f"inline constexpr double ml_probability_threshold = {model['probability_threshold']!r};",
        f"inline constexpr double ml_logit_threshold = {model['logit_threshold']!r};",
        f"inline constexpr double ml_folded_bias = {model['folded_bias']!r};",
        "inline constexpr const char *ml_feature_names[141] = {",
    ]
    lines += [f'    "{name}",' for name in model["feature_names"]]
    lines += ["};", "inline constexpr double ml_folded_weight[141] = {"]
    lines += [f"    {w!r}," for w in model["folded_weight"]]
    lines += ["};", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="fail when the checked-in table differs from the model JSON")
    args = parser.parse_args()
    text = render(MODEL.read_bytes())
    if args.check:
        if OUTPUT.read_text() != text:
            print("native model table drifted from tools/segarecomp_ml_region.model.json", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text, newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
